#!/usr/bin/env python3
"""scad_from_poly.py — poly.json → OpenSCAD stencil plate (difference extrude)."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--poly", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--name", type=str, default="stencil")
    p.add_argument("--thickness", type=float, default=None)
    p.add_argument("--corner-r", type=float, default=10.0)
    return p.parse_args()


def clean_pts(pts):
    if len(pts) >= 2 and pts[0]["x"] == pts[-1]["x"] and pts[0]["y"] == pts[-1]["y"]:
        pts = pts[:-1]
    return pts


def main() -> int:
    args = parse_args()
    meta = json.loads(args.poly.read_text(encoding="utf-8"))
    plate = float(meta["plate_mm"])
    frame = float(meta["frame_mm"])
    thick = float(args.thickness if args.thickness is not None else meta.get("thickness_hint_mm", 2.0))

    if meta.get("polygons"):
        polys = [clean_pts(p) for p in meta["polygons"]]
    else:
        polys = [clean_pts(meta["polygon"])]

    modules = []
    for i, pts in enumerate(polys):
        pairs = ",\n      ".join(f'[{p["x"]:.4f}, {p["y"]:.4f}]' for p in pts)
        modules.append(f"  polygon(points = [\n      {pairs}\n    ]);")

    body = "\n".join(modules)
    if len(polys) == 1:
        sil_body = body
    else:
        sil_body = "  union() {\n" + "\n".join(modules) + "\n  }"

    scad = f"""// Auto-generated by image-silhouette-print / scad_from_poly.py
// name={args.name}
// source={meta.get('source','')}
// hole_policy={meta.get('hole_policy')} n_polygons={len(polys)}
// print_orientation=feet-down  product_class=other  use_flip=no

plate = {plate};
thickness = {thick};
frame = {frame}; // docs only — silhouette already scaled to inner
corner_r = {args.corner_r};
$fn = 32;
eps = 0.05;

echo("image-silhouette {args.name}");
echo(str("plate=", plate, " t=", thickness, " polys=", {len(polys)}));

module soft_square(s, r) {{
  rr = min(r, s/2 - 0.01);
  offset(r = rr)
    square([s - 2*rr, s - 2*rr], center = true);
}}

module silhouette_2d() {{
{sil_body}
}}

module stencil() {{
  difference() {{
    linear_extrude(height = thickness, convexity = 10)
      soft_square(plate, corner_r);
    translate([0, 0, -eps])
      linear_extrude(height = thickness + 2*eps, convexity = 30)
        silhouette_2d();
  }}
}}

stencil();
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(scad, encoding="utf-8")
    npts = sum(len(p) for p in polys)
    print(f"scad: {args.out}  polygons={len(polys)} points={npts} plate={plate} t={thick}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
